### ISSUE TITLE
vscode未找到browse packpages选项

### ISSUE THREAD

**Issue by ekko-zhao** [chasingboy/Xtools#5]
<img width="520" alt="image" src="https://github.com/chasingboy/Xtools/assets/26781518/df28f5b1-cd9e-4ad0-94da-9b3b479beda7">
师傅你好，我的版本没有找到这个目录。
Version: 1.81.1 (Universal)
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Date: 2023-08-09T22:20:33.924Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin x64 19.6.0
还有其他方法安装吗？

**Comment by chasingboy** [comment]
是 Sublime Text 插件，不是 Vscode。
